### ISSUE TITLE
mix scenic.new scenic won't work

### ISSUE THREAD

**Issue by moperacz** [boydm/scenic_new#12]
if u try to use scenic as "application" name, compilation process hangs forever without any info why only:

```bash
$ iex -S mix
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

==> scenic
Compiling 78 files (.ex)
Generated scenic app
==> scenic
ln -fs ../static priv/
Compiling 10 files (.ex)
warning: redefining module Scenic (current version loaded from _build/dev/lib/scenic/ebin/Elixir.Scenic.beam)
  lib/scenic.ex:1

Generated scenic app

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

it should be some pointers when you create a `scenic` app using `mix scenic.new`

the underlying problem is with _your_ app beeing the Scenic module 😉

**Comment by boydm** [comment]
Good point. What do you think the warning should say?

Was evaluating making scenic itself an application, but I think it is better to make it something your app instantiates. That way the app developer has more control over any services the scenes may depend on. (talked this through with Jose. He pointed that out...)

So a better warning is in order.

**Comment by moperacz** [comment]
My input for this is: 'don't allow to create the application named scenic using mix scenic.new' as this will bring only the headake later.

or maybe inform a user that scenic_new with name scenic will not work "out of the box" as namespace from the library will be hidden by your scenic module...

and of course, You can print "this behavior is by design" :wink:

**Comment by boydm** [comment]
Ah. Now I fully understand the issue.

Naming an app Scenic is now prevented in master. This will go out soon in 0.8.0

I think the others will be less common to hit. Thank you for the discussion.
