### ISSUE TITLE
should display version

### ISSUE THREAD

**Issue by cortfritz** [boydm/scenic_new#16]
the ux should display version of the archive and also of the subcomponents such as scenic, scenic_math, etc.

possible to get a manifest at the command line?  Maybe via mix?  I don't know what is elixir idiomatic, but whatever is standard.

**Comment by gerbal** [comment]
`Application.started_applications` may do what you want.

**Comment by boydm** [comment]
This is partially fixed. The nerves sample app in the 0.9.0 shows the version. Sorta ran out of time/forgot to add it to the rest. Will do.

The api @gerbal references works, but @cortfritz wanted it to be visible in the example scene itself, which is a worthy thing to do. If I can remember to actually do it next time...

**Comment by boydm** [comment]
Fully resolved in master
