### ISSUE TITLE
Bad Library Error on `load_nifs/0`

### ISSUE THREAD

**Issue by tapickell** [boydm/scenic_new#2]
```
14:48:56.267 [error] Process #PID<0.1992.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:bad_lib, 'Library version (2.13) not compatible (with 2.12).'}}
    lib/math/matrix.ex:24: Scenic.Math.Matrix.load_nifs/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5

14:48:56.268 [warn]  The on_load function for module Elixir.Scenic.Math.Matrix returned:
{{:badmatch, {:error, {:bad_lib, 'Library version (2.13) not compatible (with 2.12).'}}}, [{Scenic.Math.Matrix, :load_nifs, 0, [file: 'lib/math/matrix.ex', line: 24]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1333]}]}
```
I followed the readme on scenic_new
and on running `iex -S mix`
I see this error in iex every time I move the cursor.
This is on OS X.
I did follow the updated instructions for deps on OSX
`brew install glfw3 glew pkg-config`
to compile.

**Comment by juhalehtonen** [comment]
Can confirm the issue on Elixir 1.7.2 and Erlang/OTP 20.0.3 using macOS 10.13.6 High Sierra.

While I can't say for certain what causes the problem per se, I fixed this by upgrading my system from Erlang/OTP `20.0.3` to Erlang/OTP `21.0.6`.  I also upgraded Elixir to 1.7.3 (from 1.7.2) while I was at it, but that shouldn't really affect what you're experiencing here.

**Comment by tapickell** [comment]
@juhalehtonen thank you I will try it on OTP 21.x.x 
```
~/code/scenic_ui_test ᐅ elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.7.0 (compiled with Erlang/OTP 20)
```

**Comment by tapickell** [comment]
```
~/code/scenic_ui_test ᐅ elixir --version
Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 19)
```
Just tested after installing 1.7.3 and this works fine now. :+1:

**Comment by boydm** [comment]
I'll add a note that it needs 21

**Comment by boydm** [comment]
Note added.
