### ISSUE TITLE
Cannot compile basic project

### ISSUE THREAD

**Issue by Awlexus** [boydm/scenic_new#4]
I tried compiling the project you get from running `mix scenix.new`, but it fails when trying to compile scenic_math.

Note: All scenic_math tests pass and trying to build scenic_math git-project works as well

Error
```
==> scenic_math
cc c_src/line.o -L/usr/lib/erlang/usr/lib -fPIC -shared  -dynamiclib -o priv/line.so
c_src/line.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [Makefile:42: priv/line.so] Error 1
could not compile dependency :scenic_math, "mix compile" failed. You can recompile this dependency with "mix deps.compile scenic_math", update it with "mix deps.update scenic_math" or clean it with "mix deps.clean scenic_math"
==> tic_tac_toe
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".
```

Version
```iex -v
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

IEx 1.7.3 (compiled with Erlang/OTP 21)```

**Comment by boydm** [comment]
Turns out I included the built Mac *.o files in scenic_math when I pushed the archive to hex. (Possibly in scenic_driver_glfw) I'll update those when I have a chance in a few hours.

In the mean time, please try going into deps (or build) not sure and deleting those files so they get rebuilt by your compiler. Might be a few hours before I can get to it...

**Comment by Awlexus** [comment]
Yeah, that did the trick. Thanks for the nimble answer!

**Comment by andyl** [comment]
I was able to get things working on Ubuntu with this:

    rm deps/scenic_path/c_src/*.o

**Comment by rrrkren** [comment]
I had to install glew and glfw3 to make it work on osx.
`brew install glfw3 glew`

**Comment by Awlexus** [comment]
@boydm just scenix_math

_Sent from my K10 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by boydm** [comment]
I just updated scenic_math, so it should work now.

Please test it for me by running this in your project.

```
mix deps.clean scenic_math
mix deps.update scenic_math
mix compile
```

**Comment by boydm** [comment]
Thank you! I'll close the issue since its resolved.
